management:
  context-path: /mgmt
  
security:
  user:
    name: admin
    password: password

spring:
  boot:
    admin:
      url: http://spring-boot-admin:8080
      auth:
        username: admin
        password: password
      notify:
        rate: 60000
        reminder:
          period: 3600000
        mail:
          enabled: false
          from:
          to:
          mailgun:
            api:
              url:
              key:
  application:
    name: spring-boot-admin
    
logging:
  level:
    org.springframework.security: INFO

zuul:
  sensitiveHeaders:
