server:
  port: 8080

management:
  context-path: /mgmt
  
security:
  user:
    name: admin
    password: password

spring:
  boot:
    admin:
      url: http://localhost:${server.port}
      username: ${security.user.name}
      password: ${security.user.password}
      client:
        service-base-url: http://localhost:${server.port}
        metadata:
          user.name: ${security.user.name}
          user.password: ${security.user.password}
      notify:
        rate: 60000
        reminder:
          period: 3600000
        mail:
          enabled: false
          from:
          to:
          mailgun:
            api:
              url:
              key:
  application:
    name: spring-boot-admin
    
logging:
  level:
    org.springframework.security: INFO

zuul:
  sensitiveHeaders:
